### PR TITLE
Added 5 demo websites to websites.yaml

### PR DESCRIPTION
**Pull request by pyxelr**
1) SegNet
2) Caffe Demos
3) LSTM Music Maker
4) OMNI Draw
5) Celeb Match

### CODE REVIEW

**Comment by stared** [comment]
Thank you!
A few remarks:

 `library` only for libraries, not things using a library. E.g. `tensorflow.js` is a library. An application using that typically isn't.

Also, I am entirely undecided if to include things that are not front-end only (and require some backend). My general impulse was to  not include these, as:

* one is not able to easily re-use them,
* they are more prone to shutdown,
* there are way too many such and it would dilute the list (de facto ALL services using ML/DL).

Yet, as I think right now - they still provide value as interactive examples. So for now we may use that, but make sure to add 'backend-dependent' or something like that in `uses`.

**Comment by pyxelr** [comment]
Right, I do was concerned what the desired criteria of the links were.
I think it might be worth adding a section of `resource criteria` in a Readme file, to clear the mind of the potential collaborators.

For now, the five links were taken from the top of my head, and I am also concerned if they fit into the list.
It is a little bit tough to find interactive applications that might fit the other examples, which are great, but I will try to remember to include something else as I approach it.

**Comment by stared** [comment]
@pyxelr Now I think it would be useful to include your stuff, as long as you add/change tags accordingly (and not linking to repo when it does not contain the service, just algorithm used).  

Right now I will try to be more inclusive and see where it goes.

(I will add criteria to README.)

**Comment by pyxelr** [comment]
@stared Right, I have just made the changes on my side. Please do correct me if I am wrong with them.

I have included the entire changelog in the latest commit description.

**Comment by stared** [comment]
@pyxelr Awesome!

**Pull request merged**
